---
- hosts: web-servers
  remote_user: ansadmin
  become: true
  tasks:
  - name: copier file source vers destination
    copy:
      src: '/home/ansadmin'
      dest: '/home/ansadmin/test'
      
 
